### ISSUE TITLE
New craftitem: clock

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#64] opened 2016-01-16 01:48 UTC
I was testing locally a very simple craftitem that will allow to do what beds do now, but is not necessary that most players agree with it. Is a clock that sets the time of day to 0.23 (just as beds do).

I would like to have it ingame. Probably set a new priv that the admin will grant to some players (though others might think is unfair), or just put it in there and don't tell anyone about it. There's no way to "missuse" this item, and will give no issues in the future due to it's simplicity.

You can see it [here](http://i.xomf.com/lcrqv.png)

**Comment by ObaniGemini** [comment] 2016-01-16 08:24
Well the problem is that some players could want to be at night. But if the craft is easier than beds, why not adding it as a replacement of beds work. Many players can't pass night just because they don't have a bed. It could also add a quest for first levels.

**Comment by BetterToAutomateTheWorld** [comment] 2016-01-16 12:46
I'm against this mod, so -1.

The subgame needs to be light, and this mod is just a bed clone with "set_time" abuse.

**Comment by rredesigns** [comment] 2016-01-16 14:25
Actually @ObaniGemini , the craft I set up requires 4 mese blocks, one diamond block, and 4 steel ingots. So is not easier to craft than beds. But of course, it can be changed. I made it hard so only advanced players will be able to craft it.

@Ombridride, the subgame will be equally light after this. And there's no "set_time abuse" as I see it, since beds do the same thing, just under different circumstances.
Some players asked for something like this, and I agree with them. At least go in game while there are a bunch of players and ask them to have a greater opinion than just us.

**Comment by Lymkwi** [comment] 2016-01-16 16:55
Well, the idea of having a clock to _see_ the curent time wouldn't be bad, but I don't see anything this clock could do that beds couldn't. Also, beds require more than 50% of players to be sleeping at the same time at night. If we follow this logic, we should have a system that makes multiple players acting together able to change time. Having a single user able to change time wouldn't be, in my opinion, such a good idea.

**Comment by rredesigns** [comment] 2016-01-16 16:57
I think it is. As I explained Obani, me and cessna are always asked to "make it day" by new users.

**Comment by Lymkwi** [comment] 2016-01-16 16:59
Okay, but then, you should do it colectively, like for beds.
Otherwise we could grant you settime but that would be unequal.

**Comment by ObaniGemini** [comment] 2016-01-16 17:02
@rredesigns : you don't get was we mean with "light". It's not just about the server performances. I'll take the example of a color pattern in graphism. You can go out of the pattern, but the pictures will not have the same look, the same spirit.
Skyblock is minetest_game, with some little adds.

The solution of your problem would be in giving `time` privilege to some people, like all of us on that repository, in fact. As it, we could moderate the server on that point. But this clock idea is not good IMO.

**Comment by rredesigns** [comment] 2016-01-16 17:39
Time priv sounds ok too for devs. I just need a fast way to set time without using spanish, english and my bad german to tell players to go to bed.

Beds are a HUGE mess. When players get to bed and nothing changes they come out, and refuse to get in, is really complicated to coordinate 7+ people speaking different languages while at the same time a bunch of them is asking you to make it day because they think you can. :p

**Comment by ObaniGemini** [comment] 2016-01-16 17:43
@rredesigns : if players can't use bed, so we have to set time by ourself for them or for us. There's no other solution. When someone asks the others to go to bed, you can still ask if someone doesn't want to be to bed and set time to day. But allowing every player to choose whenever they want to change time to day is not possible to do. It would turn into an incredible mess. We only can give that privilege to responsible players like you, but not to everyone.

**Comment by rredesigns** [comment] 2016-01-16 17:55
@ObaniGemini I understand. That's why I made a super difficult, super expensive craft, to limit the access to new players. But if admin is ok with granting devs with time priv, then is equally useful.

**Comment by ObaniGemini** [comment] 2016-01-16 18:43
@rredesigns We'll ask him as a top priority. || https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/66 || Please support if you think it's a good idea :)

**Comment by rredesigns** [comment] 2016-01-16 19:03
Is a good idea. :D

**Comment by BetterToAutomateTheWorld** [comment] 2016-01-18 08:34
If i understand well, the night is a problem for all players ?
If yes, we can easily erase the night

**Comment by rredesigns** [comment] 2016-01-18 14:08
No, not for all of them.

**Comment by BetterToAutomateTheWorld** [comment] 2016-01-18 14:53
I discuss it with @gravgun we surely have a way to reduce the night time proportionally to the day time

Actually it's 50% day & 50% night, and maybe it will be interesting to do 1/3 night & 2/3 day, or 1/4 night & 3/4 day 
The clock and give the "time" privileges aren't good solutions

**Comment by BetterToAutomateTheWorld** [comment] 2016-02-02 21:25
The clock item won't be added, we will prefer a shorter night system based.

I closed this issue

**Closed as completed** 2016-02-02 21:25 UTC
Labels: Modding, Priority: Low
