### ISSUE TITLE
All servers down!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#229] opened 2017-08-25 23:33 UTC
@Darcidride All the servers are down.
:large_orange_diamond:

**Comment by arielenter** [comment] 2017-08-26 15:50
I can confirmed. It's being like this since yesterday :S , the server is down.

**Comment by BetterToAutomateTheWorld** [comment] 2017-09-04 17:49
Fixed since a long time, sorry i close the issue now :)

**Closed as completed by BetterToAutomateTheWorld** 2017-09-04 17:49 UTC
Labels: Priority: High, Server crash
